extends:
- standard
- standard-react
parser:
  babel-eslint
rules:
  object-curly-spacing: [ error, always ]
  react/prop-types: off
  space-before-function-paren: off
  import/first: off
  import/no-webpack-loader-syntax: off
globals:
  React: false
plugins:
    - import